all:
  children:
    web_servers:
      hosts:
        web_server_no1:
          ansible_host: ec2-*****.ap-south-1.compute.amazonaws.com 
        web_server_no2:
          ansible_host: ec2-*****.ap-south-1.compute.amazonaws.com
    app_servers:
      hosts:
        app_server_1:
          ansible_host: ec2-*****.ap-south-1.compute.amazonaws.com
        app_server_2:
          ansible_host: ec2-*****.ap-south-1.compute.amazonaws.com
  vars:
    ansible_user: ubuntu #user
    ansible_port: 22     #ssh-port
    ansible_ssh_private_key_file: ansible-tutorial.pem #keyfilepath
prod:
  children:
    web_servers:
    app_servers:
